# prometheus.yml

# Place in same directory as docker-compose.yml and replace $DOCKERHOST with your desired host IP where ceph_exporter is running

global:
    scrape_interval: 5s
    external_labels:
        monitor: my-monitor
scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets: ['localhost:9090']
    - job_name: ceph-exporter
      static_configs:
          - targets: ['$DOCKERHOST:9128']
      metric_relabel_configs:
          - source_labels: [topology]
            regex:         '.*,root=([\w\-]+),.*'
            target_label:  'root'
            replacement:   '$1'
          - source_labels: [topology]
            regex:         '.*,room=([\w\-]+),.*'
            target_label:  'room'
            replacement:   '$1'
          - source_labels: [topology]
            regex:         '.*,host=([\w\-]+),.*'
            target_label:  'host'
            replacement:   '$1'
          - regex: 'topology'
            action: labeldrop
